export interface WorkStatus {
  employeeId: string;
  project: string;
  task: string;
  status: 'In Progress' | 'Completed' | 'On Hold' | 'Review';
  progress: number; // 0-100
  dueDate: string;
  priority: 'High' | 'Medium' | 'Low';
}

export const WORK_STATUSES: WorkStatus[] = [
  { employeeId: 'CBHYD604', project: 'DCT', task: 'NCD Integration Services', status: 'In Progress', progress: 60, dueDate: '2025-07-30', priority: 'High' },
  { employeeId: 'CBHYD605', project: 'ERP', task: 'CBS Integration Module', status: 'Review', progress: 85, dueDate: '2025-07-25', priority: 'High' },
  { employeeId: 'CBHYD621', project: 'DCT', task: 'OpenKM Document Flow', status: 'In Progress', progress: 50, dueDate: '2025-08-05', priority: 'Medium' },
  { employeeId: 'CBHYD626', project: 'Insight', task: 'Electron Desktop Build', status: 'On Hold', progress: 30, dueDate: '2025-08-15', priority: 'Low' },
  { employeeId: 'CBHYD627', project: 'CoopsIndia', task: 'PostgreSQL Migration', status: 'In Progress', progress: 45, dueDate: '2025-08-01', priority: 'Medium' },
  { employeeId: 'CBHYD628', project: 'DCT', task: 'TN Migration Backend', status: 'In Progress', progress: 65, dueDate: '2025-07-28', priority: 'High' },
  { employeeId: 'CBHYD629', project: 'TIHCL', task: 'FHR Report Generation', status: 'Review', progress: 90, dueDate: '2025-07-22', priority: 'High' },
  { employeeId: 'CBHYD631', project: 'ERP', task: 'NCD Integration Services', status: 'In Progress', progress: 55, dueDate: '2025-08-08', priority: 'Medium' },
  { employeeId: 'CBHYD640', project: 'FHR', task: 'PACS DCT Data Mapping', status: 'Completed', progress: 100, dueDate: '2025-07-20', priority: 'High' },
  { employeeId: 'CBHYD642', project: 'TIHCL', task: 'Microservices API Layer', status: 'In Progress', progress: 72, dueDate: '2025-07-29', priority: 'High' },
  { employeeId: 'CBHYD643', project: 'ERP', task: 'Mobile App Services', status: 'In Progress', progress: 40, dueDate: '2025-08-12', priority: 'Medium' },
  { employeeId: 'CBHYD644', project: 'DCT', task: 'iText PDF Reports', status: 'Review', progress: 88, dueDate: '2025-07-24', priority: 'High' },
  { employeeId: 'CBHYD645', project: 'ERP', task: 'Kafka Event Streaming', status: 'In Progress', progress: 58, dueDate: '2025-08-03', priority: 'Medium' },
  { employeeId: 'CBHYD646', project: 'DCT', task: 'DCT-ERP Migration', status: 'In Progress', progress: 48, dueDate: '2025-08-07', priority: 'Medium' },
  { employeeId: 'CBHYD647', project: 'ARDB-DCT', task: 'DCT Migration Scripts', status: 'On Hold', progress: 25, dueDate: '2025-08-20', priority: 'Low' },
  { employeeId: 'CBHYD648', project: 'ERP', task: 'Jenkins CI/CD Pipeline', status: 'In Progress', progress: 62, dueDate: '2025-07-31', priority: 'High' },
  { employeeId: 'CBHYD649', project: 'DCT', task: 'Shell Script Automation', status: 'Completed', progress: 100, dueDate: '2025-07-18', priority: 'Medium' },
  { employeeId: 'CBHYD650', project: 'ARDB', task: 'JUnit & Mockito Tests', status: 'In Progress', progress: 68, dueDate: '2025-07-27', priority: 'Medium' },
  { employeeId: 'CBHYD655', project: 'ERP', task: 'MSSQL Data Validation', status: 'Review', progress: 80, dueDate: '2025-07-23', priority: 'High' },
  { employeeId: 'CBHYD656', project: 'DCT', task: 'Oracle DB Integration', status: 'In Progress', progress: 53, dueDate: '2025-08-06', priority: 'Medium' },
  { employeeId: 'CBHYD680', project: 'ERP', task: 'Regression Testing Suite', status: 'In Progress', progress: 44, dueDate: '2025-08-09', priority: 'High' },
  { employeeId: 'CBHYD681', project: 'DCT', task: 'UAT Test Cases', status: 'In Progress', progress: 38, dueDate: '2025-08-11', priority: 'Medium' },
  { employeeId: 'CBHYD682', project: 'TIHCL', task: 'Bug Tracking & Reporting', status: 'On Hold', progress: 20, dueDate: '2025-08-18', priority: 'Low' },
  { employeeId: 'CBHYD638', project: 'ERP', task: 'Automation Test Scripts', status: 'In Progress', progress: 57, dueDate: '2025-08-02', priority: 'Medium' },
  { employeeId: 'CBHYD652', project: 'ARDB-DCT', task: 'Manual Test Execution', status: 'Completed', progress: 100, dueDate: '2025-07-19', priority: 'High' },
  { employeeId: 'CBHYD620', project: 'ERP', task: 'UI Wireframes & Figma', status: 'In Progress', progress: 75, dueDate: '2025-07-26', priority: 'High' },
  { employeeId: 'CBHYD636', project: 'DCT', task: 'Photoshop Asset Design', status: 'Review', progress: 92, dueDate: '2025-07-21', priority: 'Medium' },
  { employeeId: 'CBHYD367', project: 'FHR', task: 'Adobe Illustrator Icons', status: 'Completed', progress: 100, dueDate: '2025-07-17', priority: 'Low' },
  { employeeId: 'CBHYD639', project: 'ERP', task: 'Angular Component Library', status: 'In Progress', progress: 66, dueDate: '2025-07-30', priority: 'High' },
  { employeeId: 'CBHYD657', project: 'ERP', task: 'React JS Dashboard UI', status: 'In Progress', progress: 42, dueDate: '2025-08-13', priority: 'Medium' },
  { employeeId: 'CBHYD658', project: 'ERP', task: 'Bootstrap Responsive Layout', status: 'Review', progress: 83, dueDate: '2025-07-24', priority: 'Medium' },
  { employeeId: 'CBHYD659', project: 'ERP', task: 'Angular Forms & Validation', status: 'In Progress', progress: 49, dueDate: '2025-08-04', priority: 'Medium' },
  { employeeId: 'CBHYD661', project: 'ERP', task: 'Figma to Angular Conversion', status: 'In Progress', progress: 61, dueDate: '2025-07-29', priority: 'High' },
  { employeeId: 'CBHYD653', project: 'Infra Support', task: 'Azure Cloud Monitoring', status: 'In Progress', progress: 55, dueDate: '2025-08-05', priority: 'High' },
  { employeeId: 'CBHYD662', project: 'DevOps', task: 'Docker & Jenkins Pipeline', status: 'In Progress', progress: 47, dueDate: '2025-08-08', priority: 'High' },
];

export interface Employee {
  id: string;
  name: string;
  role: string;
  department: string;
  email: string;
  phone?: string;
  skills?: string;
  projects?: string;
  gender?: 'male' | 'female';
  about?: string;
  facts?: { icon: string; label: string; value: string }[];
  avatar?: string;
}

export const EMPLOYEES: Employee[] = [
  {
    id: 'CBHYD601',
    name: 'Bagadi Balakrishna',
    role: 'Project Manager',
    department: 'Management',
    email: 'balakrishna.bagadi@intellectinfo.com',
    phone: '+91 98765 00001',
    gender: 'male',
    avatar: 'assets/images/bala.jpeg',
    about: `Bagadi Balakrishna is a seasoned Project Manager at Intellect Information Technologies, driving the successful delivery of large-scale cooperative banking and ERP solutions across India. With a sharp eye for detail and a people-first leadership style, he bridges the gap between technical teams and business stakeholders — ensuring every project is delivered on time, within scope, and beyond expectations.`,
    facts: [
      { icon: '🏆', label: 'Projects Delivered', value: '15+ Enterprise Projects' },
      { icon: '👥', label: 'Team Managed', value: '36 Members Across 5 Departments' },
      { icon: '🌍', label: 'Domain Expertise', value: 'Cooperative Banking & ERP Systems' },
      { icon: '⚡', label: 'Superpower', value: 'Turning chaos into clear roadmaps' },
      { icon: '📋', label: 'Methodology', value: 'Agile / Scrum / Waterfall' },
      { icon: '💡', label: 'Passion', value: 'Building high-performance teams' },
    ],
  },
  {
    id: 'CBHYD604',
    name: 'Vaddi Navya Sree',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00002',
    email: 'navyasree.vaddi@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, Kafka, Jasper Reports, OpenKM',
    projects: 'DCT, ARDB-DCT, FHR-Training, NCD Integration Services, Mobile Application Services (TG and Members), e-KYC Services, CBS Integrations, Share Management',
    gender: 'female',
    avatar: 'assets/images/Navya22.jpg',
  },
  {
    id: 'CBHYD605',
    name: 'Yarlanki Siva Kumar',
    role: 'Full-stack Developer',
    phone: '+91 98765 00003',
    department: 'Software Engineering',
    email: 'sivakumar.yarlanki@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, Kafka, Jasper Reports, OpenKM, Redis Cache',
    projects: 'CoopsIndia, DCT Migration, ARDB, ERP, TIHCL, CBS Integration, Insight',
    gender: 'male',
    avatar: 'assets/images/SivaKumar.jpg',
  },
  {
    id: 'CBHYD621',
    name: 'Thakkallapalli Phanidher',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00004',
    email: 'phanidher.thakkallapalli@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, Kafka, Jasper Reports, Thymeleaf, OpenKM',
    projects: 'CoopsIndia, OpenKM, Insight, DCT, ARDB, ERP, CBS Integration, Mobile Application Services',
    gender: 'male',
    avatar: 'assets/images/phani.JPG',
  },
  {
    id: 'CBHYD626',
    name: 'Bora Kiran Kumar',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00005',
    email: 'kirankumar.bora@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, Electron, Ionic, Kafka, Jasper Reports',
    projects: 'Insight, CoopsIndia, DCT, TIHCL, ERP',
    gender: 'male',
    avatar: 'assets/images/kiran.png',
  },
  {
    id: 'CBHYD627',
    name: 'Aravind Gundu',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00006',
    email: 'aravind.gundu@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, Kafka, Jasper Reports, PostgreSQL',
    projects: 'Insight, CoopsIndia, DCT, ARDB, ERP',
    gender: 'male',
    avatar: 'assets/images/Aravind.png',
  },
  {
    id: 'CBHYD628',
    name: 'Pedakota Uday Kumar',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 9908660573',
    email: 'udaykumar.pedakota@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, JavaScript, Jasper Reports, Thymeleaf, Kafka, Postman, Swagger',
    projects: 'TIHCL, DCT, FHR, ERP, TN Migration, DCT Migration',
    gender: 'male',
    avatar: 'assets/images/uday_pedakot.png',
  },
  {
    id: 'CBHYD629',
    name: 'Tankala Tirupati Raju',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00008',
    email: 'tirupatiraju.tankala@intellectinfo.com',
    skills: 'Java, Spring Boot, MySQL, Angular, Kafka, Jasper Reports, Thymeleaf',
    projects: 'TIHCL, DCT, FHR, ARDB-DCT',
    gender: 'male',
    avatar: 'assets/images/tirupatiraju.png',
  },
  {
    id: 'CBHYD631',
    name: 'Mamidi Nani',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00009',
    email: 'nani.mamidi@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, Kafka, Jasper Reports',
    projects: 'CoopsIndia, TIHCL, ARDB, ERP, NCD Integration Services',
    gender: 'male',
    avatar: 'assets/images/Nani.png',
  },
  {
    id: 'CBHYD640',
    name: 'Karthik Jakkula',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00010',
    email: 'karthik.jakkula@intellectinfo.com',
    skills: 'Java, Spring, MySQL, MSSQL, PostgreSQL, Excel/Spreadsheet, Postman, Swagger, Manual Testing, PACS Domain Knowledge',
    projects: 'FHR, TIHCL, PACS DCT, ARDB DCT, TN-ERP Migration, DCT-ERP Migration, DCT-DCT Migration, TG Mobile Application, ERP, MSSQL-MySQL ERP Migration',
    gender: 'male',
    avatar: 'assets/images/Karthk.png',
  },
  {
    id: 'CBHYD642',
    name: 'Siddi Amulya',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00011',
    email: 'amulya.siddi@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, Kafka, Microservices, Dynamic Jasper Reports',
    projects: 'TIHCL, FHR, DCT, ARDB-DCT',
    gender: 'female',
    avatar: 'assets/images/Amulya.jpeg',
  },
  {
    id: 'CBHYD643',
    name: 'Dilip Kumar Gurijala',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00012',
    email: 'dilipkumar.gurijala@intellectinfo.com',
    skills: 'HTML, CSS, Java, Spring, MySQL, Microservices, Shell Script (Basics), iText PDF',
    projects: 'ERP, DCT, FHR, Mobile Application Services (TG and Members)',
    gender: 'male',
    avatar: 'assets/images/Dileep gurjala.png',
  },
  {
    id: 'CBHYD644',
    name: 'Kotturu Saikumar',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 9381660617',
    email: 'saikumar.kotturu@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, iText PDF, Microservices, Shell Script (Basics)',
    projects: 'ERP, DCT, FHR, Mobile Application Services',
    gender: 'male',
    avatar: 'assets/images/Saikumar.png',
  },
  {
    id: 'CBHYD645',
    name: 'Gedela Dileep Kumar',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00014',
    email: 'dileepkumar.gedela@intellectinfo.com',
    skills: 'Java, Spring, MySQL, HTML, CSS, JavaScript, Angular, Microservices, Kafka, Jenkins, Shell Script (Basics)',
    projects: 'ERP, DCT, FHR, ARDB, Mobile Application Services',
    gender: 'male',
    avatar: 'assets/images/Dileep Gadala.png',
  },
  {
    id: 'CBHYD646',
    name: 'Laxmi Prasanna Kumar S',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00015',
    email: 'laxmiprasanna.s@intellectinfo.com',
    skills: 'Java, Spring, MySQL, HTML, CSS, Angular, Jenkins, Shell Script (Basics)',
    projects: 'DCT, ARDB-DCT, DCT-ERP Migration, ERP',
    gender: 'male',
    avatar: 'assets/images/Prasanna.png',
  },
  {
    id: 'CBHYD647',
    name: 'Bagadi Jogarao',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00016',
    email: 'jogarao.bagadi@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, JUnit, Jenkins, AWT, Swing',
    projects: 'DCT, ARDB-DCT, ERP, DCT Migration',
    gender: 'male',
    avatar: 'assets/images/jogarao.png',
  },
  {
    id: 'CBHYD648',
    name: 'Sahukari Praveen Chowdary',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00017',
    email: 'praveenchowdary.sahukari@intellectinfo.com',
    skills: 'Java, Spring, MySQL, HTML, CSS, Angular, Jenkins, Shell Script',
    projects: 'ERP, DCT, ARDB-DCT, DCT-ERP Migration',
    gender: 'male',
    avatar: 'assets/images/Praveen.JPG',
  },
  {
    id: 'CBHYD649',
    name: 'Korla Ramu',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00018',
    email: 'ramu.korla@intellectinfo.com',
    skills: 'Java, Spring, MySQL, HTML, CSS, Angular, Shell Script (Basics), Jenkins',
    projects: 'DCT, ERP, ARDB-DCT, DCT-ERP Migration',
    gender: 'male',
    avatar: 'assets/images/Ramu.png',
  },
  {
    id: 'CBHYD650',
    name: 'Bhavana Maddamsetty',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00019',
    email: 'bhavana.maddamsetty@intellectinfo.com',
    skills: 'Java, Spring, MySQL, AWT, Swing, Angular, JUnit, Mockito, Jenkins',
    projects: 'ARDB, DCT, ARDB-DCT, ERP, DCT-ERP Migration',
    gender: 'female',
    avatar: 'assets/images/Bavana.png',
  },
  {
    id: 'CBHYD655',
    name: 'Malla Akhila',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00020',
    email: 'akhila.malla@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, MSSQL, JUnit Testing',
    projects: 'DCT, ERP, ARDB, FHR',
    gender: 'female',
    avatar: 'assets/images/Akhila.png',
  },
  {
    id: 'CBHYD656',
    name: 'Kallepilli Yamuna',
    role: 'Full-stack Developer',
    department: 'Software Engineering',
    phone: '+91 98765 00021',
    email: 'yamuna.kallepilli@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Angular, JavaScript, Microservices, Oracle Database, iText PDF, Swagger, Postman',
    projects: 'DCT, ERP, ARDB, FHR',
    gender: 'female',
    avatar: 'assets/images/Yamuna.jpg',
  },
  {
    id: 'CBHYD680',
    name: 'Kusuma',
    role: 'Tester',
    department: 'Testing',
    phone: '+91 98765 00022',
    email: 'kusuma@intellectinfo.com',
    skills: 'Manual Testing, MySQL, Basic Java, Automation Testing, Bugzilla, Jira',
    projects: 'TIHCL, DCT, ERP',
    gender: 'female',
  },
  {
    id: 'CBHYD681',
    name: 'Sandhya',
    role: 'Tester',
    department: 'Testing',
    phone: '+91 98765 00023',
    email: 'sandhya@intellectinfo.com',
    skills: 'Manual Testing, MySQL, Basic Java, Automation Testing, Bugzilla, Jira',
    projects: 'TIHCL, DCT, ERP',
    gender: 'female',
  },
  {
    id: 'CBHYD682',
    name: 'Mudhukar',
    role: 'Tester',
    department: 'Testing',
    phone: '+91 98765 00024',
    email: 'mudhukar@intellectinfo.com',
    skills: 'Manual Testing, MySQL, Basic Java, Automation Testing, Bugzilla, Jira',
    projects: 'TIHCL, DCT, ERP',
    gender: 'male',
  },
  {
    id: 'CBHYD638',
    name: 'Talluri Prudhvi',
    role: 'Tester',
    department: 'Testing',
    phone: '+91 98765 00025',
    email: 'prudhvi.talluri@intellectinfo.com',
    skills: 'Manual Testing, MySQL, Basic Java, Automation Testing, Bugzilla, Jira',
    projects: 'TIHCL, DCT, ERP',
    gender: 'male',
    avatar: 'assets/images/Prudhvi.png',
  },
  {
    id: 'CBHYD652',
    name: 'Avidi Rajesh',
    role: 'Tester',
    department: 'Testing',
    phone: '+91 98765 00026',
    email: 'rajesh.avidi@intellectinfo.com',
    skills: 'Manual Testing, MySQL, Java (Basics), Automation Testing (Basics)',
    projects: 'DCT, ARDB-DCT',
    gender: 'male',
    avatar: 'assets/images/Rajesh.png',
  },
  {
    id: 'CBHYD620',
    name: 'Degala Sriramamurty',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 98765 00027',
    email: 'sriramamurty.degala@intellectinfo.com',
    skills: 'HTML5, CSS, Bootstrap, JavaScript, Adobe Photoshop, PPT, UI/UX, Figma, Adobe Illustrator',
    projects: 'CoopsIndia (FHR Nation), DCT, ARDB, ERP, TIHCL, FHR',
    gender: 'male',
    avatar: 'assets/images/Sriram.png',
  },
  {
    id: 'CBHYD636',
    name: 'Chatti Raviteja',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 98765 00028',
    email: 'raviteja.chatti@intellectinfo.com',
    skills: 'HTML, CSS, Bootstrap, JavaScript, Photoshop, PPT, UI/UX, Figma',
    projects: 'TIHCL, DCT, FHR, ERP, ARDB',
    gender: 'male',
    avatar: 'assets/images/Raviteja.png',
  },
  {
    id: 'CBHYD367',
    name: 'Pachiripalli Subhash Bhargav',
    role: 'UI/UX Designer',
    department: 'Design',
    phone: '+91 98765 00029',
    email: 'subhash.pachiripalli@intellectinfo.com',
    skills: 'HTML5, CSS, Bootstrap, JavaScript, Figma, Adobe Illustrator, Adobe Photoshop, PPT, UI/UX',
    projects: 'FHR, CoopsIndia, ARDB, TIHCL, DCT, ERP',
    gender: 'male',
    avatar: 'assets/images/Subhash.png',
  },
  {
    id: 'CBHYD639',
    name: 'Kodavali Bhargavi',
    role: 'UI Developer',
    department: 'UI Development',
    phone: '+91 98765 00030',
    email: 'bhargavi.kodavali@intellectinfo.com',
    skills: 'HTML, CSS, JavaScript, Angular, Java, MySQL',
    projects: 'ERP, DCT, FHR, ARDB',
    gender: 'female',
    avatar: 'assets/images/Bharajavi.png',
  },
  {
    id: 'CBHYD657',
    name: 'Gayatri Swain',
    role: 'UI Developer',
    department: 'UI Development',
    phone: '+91 98765 00031',
    email: 'gayatri.swain@intellectinfo.com',
    skills: 'Java, Spring, MySQL, Oracle Database, Angular, React JS, HTML, CSS, JavaScript',
    projects: 'ERP',
    gender: 'female',
  },
  {
    id: 'CBHYD658',
    name: 'Polaki Krishnaveni',
    role: 'UI Developer',
    department: 'UI Development',
    phone: '+91 98765 00032',
    email: 'krishnaveni.polaki@intellectinfo.com',
    skills: 'HTML, CSS, JavaScript, Angular, Java, Bootstrap',
    projects: 'ERP',
    gender: 'female',
  },
  {
    id: 'CBHYD659',
    name: 'Maramreddy Lakshmi',
    role: 'UI Developer',
    department: 'UI Development',
    phone: '+91 98765 00033',
    email: 'lakshmi.maramreddy@intellectinfo.com',
    skills: 'HTML, CSS, JavaScript, Angular, Java, MySQL',
    projects: 'ERP',
    gender: 'female',
  },
  {
    id: 'CBHYD661',
    name: 'Srinivas Chintapenta',
    role: 'UI Developer',
    department: 'UI Development',
    phone: '+91 98765 00034',
    email: 'srinivas.chintapenta@intellectinfo.com',
    skills: 'HTML, CSS, JavaScript, Angular, Java, Figma, UI/UX',
    projects: 'ERP',
    gender: 'male',
  },
  {
    id: 'CBHYD653',
    name: 'Ogirala Vinod Chandra',
    role: 'Network',
    department: 'Infrastructure',
    phone: '+91 98765 00035',
    email: 'vinod.ogirala@intellectinfo.com',
    skills: 'Windows, VM Ware, Citrix, MSSQL, IIS, Application Management, App Package, Flex App, App-V, End User Computing, Azure Cloud, Citrix Cloud, AWS, Nutanix, Jenkins, Nexus, GitLab, SonarQube, Bugzilla',
    projects: 'Infra Support for AP DCT, FHR, ARDB, UK DCT',
    gender: 'male',
  },
  {
    id: 'CBHYD662',
    name: 'Venkatesh Mutyala',
    role: 'Network',
    department: 'Infrastructure',
    phone: '+91 98765 00036',
    email: 'venkatesh.mutyala@intellectinfo.com',
    skills: 'DevOps: Linux, Git, Maven, Jenkins, Nexus, Docker (Basics), Ansible (Basics), Kubernetes (Basics), Java (Basics), UI (Basics)',
    projects: 'Infrastructure & DevOps Support',
    gender: 'male',
  },
  {
    id: 'CBHYD663',
    name: 'Sai Teja',
    role: 'UI Developer',
    department: 'UI Development',
    phone: '+91 98765 00036',
    email: 'saiteja@intellectinfo.com',
    skills: 'HTML, CSS, JavaScript, Angular, Java, Figma, UI/UX',
    projects: 'Infrastructure & DevOps Support',
    gender: 'male',
  },
  {
    id: 'CBHYD664',
    name: 'Visruth',
    role: 'UI Developer',
    department: 'UI Development',
    phone: '+91 98765 00036',
    email: 'visruth@intellectinfo.com',
    skills: 'HTML, CSS, JavaScript, Angular, Java, Figma, UI/UX',
    projects: 'ERP',
    gender: 'male',
  },
];
